// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.Data;

#nullable disable

namespace Project1.Migrations
{
    [DbContext(typeof(Project1DbContext))]
    [Migration("20251205135540_new version of walk")]
    partial class newversionofwalk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project1.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d8f8c2e-1c4b-4d6a-9f3a-1a2b3c4d5e6f"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-4a7b-8c9d-1234567890ab"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("abcdef12-3456-7890-abcd-ef1234567890"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("Project1.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b672d11-62db-4375-d447-08de33ff7d41"),
                            Code = "RID",
                            Name = "Riyadh",
                            RegionImageUrl = "https://content.r9cdn.net/rimg/dimg/7d/60/488863c5-city-35744-16935f1b104.jpg?crop=true&width=1366&height=768&xhint=1725&yhint=1010"
                        },
                        new
                        {
                            Id = new Guid("d31571fa-ccd2-41a8-d448-08de33ff7d41"),
                            Code = "JED",
                            Name = "Jeddah",
                            RegionImageUrl = "https://images.locationscout.net/2020/03/the-read-sea-saudi-arabia-hrrc.webp?h=1400&q=80"
                        },
                        new
                        {
                            Id = new Guid("c9556526-4b65-40e0-d449-08de33ff7d41"),
                            Code = "DAM",
                            Name = "Dammam",
                            RegionImageUrl = "https://excursionmania.com/cdn-cgi/image/quality=75,format=webp,w=auto,h=auto,fit=scale-down,trim=border/https://excursionmania.com/uploads/blog/ideas/5b70a44f601894b4d4488bafc7ba3a7c.jpg"
                        },
                        new
                        {
                            Id = new Guid("f2688dad-8762-4b3d-d44a-08de33ff7d41"),
                            Code = "MEC",
                            Name = "Mecca",
                            RegionImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPCPg1rQ5JXdtzMQmf_L5xrveh6o5vZMDgxQ&s"
                        });
                });

            modelBuilder.Entity("Project1.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LengthInKm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("Project1.Models.Domain.Walk", b =>
                {
                    b.HasOne("Project1.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project1.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
